### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by enterprisebug** [JonRobo/robopython#2]
The code i am trying to execute is:

    from robopython import Robo

    BLE_Name = "tom"
    Robo = Robo(BLE_Name)
    print Robo.battery_level()

but i does not print the battery level.

Instead i get this errror:

    Running on Linux, please ensure your BLED112 dongle is plugged in
    Connected to RW_tom!
    Exception in thread Thread-6:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
    File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
    File "/home/pi/.local/lib/python2.7/site-packages/robopython/pygatt/backends/bgapi/bgapi.py", line 600, in _receive
        bytearray(args['value']))
    File "/home/pi/.local/lib/python2.7/site-packages/robopython/pygatt/device.py", line 226, in receive_notification
        callback(handle, value)
    File "/home/pi/.local/lib/python2.7/site-packages/robopython/robopython.py", line 207, in handle_rx_data
        self.update_build(read_data)
    File "/home/pi/.local/lib/python2.7/site-packages/robopython/robopython.py", line 246, in update_build
        name = self.build_map[idx][idy].name
    AttributeError: 'NoneType' object has no attribute 'name'

From what i understand:

1. I was able to connect via bluetooth: `Connected to RW_tom!` (in that moment it also plays a sound)
2. I was *not* able to call any method on `Robo`

may you give me some guidance how to proceed?
Can you give me a hint what the problem might be?

OS Info:
- Distributor ID: Raspbian
- Description: Raspbian GNU/Linux 10 (buster)
- Release: 10
- Codename: buster

Python Version:
- Python 2.7.16

Kernel Info:
- Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux

**Comment by enterprisebug** [comment]
Problem solved now.

Here are the details for documentation purposes.
- commit https://github.com/JonRobo/robopython/commit/b5da455600bfaf4cb65b5b6ec2f217a4d10b7b7d fixed the issue. I am able to play a sound on the rover!
- I am using a raspberry pi 3B+ with a BLED112 dongle. The dongle never showed up on the pi using `lsusb`. This was solved by simple using the *original* power supply.

**Comment by JonRobo** [comment]
Hello,

Commit [b5da455 ](https://github.com/JonRobo/robopython/commit/b5da455600bfaf4cb65b5b6ec2f217a4d10b7b7d) had additional code to complete the routines that handle Robo's build. Now it should not only compile but provide real-time updates to what modules are connected as well as total build on request.
